source 'https://rubygems.org'

gem 'rails', '5.2.2.1'
gem 'rspec-rails', '~> 3.1'
gem 'sqlite3', '~> 1.3.6'

group :development do
  gem 'spring'
end

group :test do
  gem 'database_cleaner'
  gem 'capybara'
end
